### ISSUE TITLE
Package as Flatpak

### ISSUE THREAD

**Issue by vega-d** [levovix0/DMusic#10]
**Is your feature request related to a problem? Please describe.**
Dependencies like libQT move on and are not always present in an expected way on the host system, so the app breaks itself overtime.

**Describe the solution you'd like**
package the app into a flatpak. 

**Describe alternatives you've considered**
snaps? only really available on ubuntu. AppImages? Also depend on stuff like libfuse2. 

**Additional context**
Right now latest release doesn't work on linux at all because libQt5Gui.so.5 is not available without installing more packages anymore. A single flatpak would allow the app to work on linux for ages to come.

**Comment by psydvl** [comment]
```
$ flatpak install org.kde.Sdk/x86_64/5.15
Looking for matches…

Info: runtime org.kde.Sdk branch 5.15 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK

Info: runtime org.freedesktop.Platform.VAAPI.Intel branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.

Info: runtime org.freedesktop.Platform.GL.default branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.

[...]
```
Maybe replace with `5.15-22.08`?
