### ISSUE TITLE
После авторизации не появляются плейлисты (windows)

### ISSUE THREAD

**Issue by Pushkin31** [levovix0/DMusic#26]
После ввода корректного токена (проверен на linux) - не появляются плейлисты на главной.

<details>
<summary>скрин</summary>

![image](https://user-images.githubusercontent.com/35974828/224562933-6d403d7f-9dfc-4565-9853-06ca60ab5b3f.png)

![image](https://user-images.githubusercontent.com/35974828/224562739-30afd165-881f-420e-9f90-68b6244ebe7f.png)

</details>

Как задебажить ошибку - не знаю.

<details>
<summary>Харки</summary>

![image](https://user-images.githubusercontent.com/35974828/224562882-136c8a65-ab55-45e5-8548-83348b46b868.png)

Python 3.9.10
</details>

**Comment by bropines** [comment]
Аналогично

**Comment by eternalyoung** [comment]
На 11 винде эта же проблема
<details>
<summary>Пустота</summary>

![image](https://github.com/levovix0/DMusic/assets/81143241/710b9851-9be8-40d2-b3ad-8fe1926e9e78)
</details>
<details>

<summary>Вход выполнен</summary>

![image](https://github.com/levovix0/DMusic/assets/81143241/1100b51c-ebfb-42c2-8113-9c5a74fe449c)
</details>
<details>
<summary>Винда</summary>

![image](https://github.com/levovix0/DMusic/assets/81143241/f7545191-c81d-49b4-babf-80a294dc0fe1)
</details>

**Comment by levovix0** [comment]
Должно было исправится в обновленной сборке 0.4 релиза

**Comment by bropines** [comment]
> Должно было исправится в обновленной сборке 0.4 релиза

НУ как ты заметил, не воркает. Мейби апи немного изменился, проверь, тыж разраб

**Comment by eternalyoung** [comment]
> Должно было исправится в обновленной сборке 0.4 релиза

Привет, это как раз на последнем релизе 0.4

**Comment by levovix0** [comment]
> НУ как ты заметил, не воркает. Мейби апи немного изменился, проверь, тыж разраб

> Привет, это как раз на последнем релизе 0.4

Я имею в виду, что добавил в 0.4 релиз файл DMusic-windows-updated.zip, в котором исправил баг.

**Comment by eternalyoung** [comment]
> Я имею в виду, что добавил в 0.4 релиз файл DMusic-windows-updated.zip, в котором исправил баг.

Скачал, вошел, до сих пор пусто, ничего не изменилось

**Comment by levovix0** [comment]
Попробуйте запустить в консоли что-то типа
```bat
dmusic.exe download 87086984
```

**Comment by eternalyoung** [comment]
>Попробуйте запустить в консоли что-то типа
> ```dmusic.exe download 87086984```

Ничего не происходит, пустой вывод
```
D:\Stuff\DMusic>dmusic.exe download 87086984

```
В самом приложении при нажатии на `загружено` ошибка:
![image](https://github.com/levovix0/DMusic/assets/81143241/fa4ea867-f1ce-4c37-b4d4-d06dfe039c59)
Еще заметил что тема приложения сбивается после его перезапуска (Аккаунт остается)

Может быть это из-за пути установки

**Comment by levovix0** [comment]
Добавил к релизу отладочные сборки, в них должно что-нибудь в консоль выводить

**Comment by eternalyoung** [comment]
> Добавил к релизу отладочные сборки, в них должно что-нибудь в консоль выводить

На дэбаг сборке всё заработало

**Comment by eternalyoung** [comment]
В консольке кроме запросов есть еще две строчки:
```
QQmlEngine::setContextForObject(): Object already has a QQmlContext
qrc:/qml/pages/MainPage.qml:36:9: QML Grid: Binding loop detected for property "columns"
```
