### ISSUE TITLE
DMusic process stops immediately

### ISSUE THREAD

**Issue by Mostik** [levovix0/DMusic#3]
**Describe the bug**
When run DMusic.exe process stops immediately. DMusic window don't show

**To Reproduce**
1. Download Release archive
2. Unpacked the archive
3. Run DMusic.exe
4. DMusic window don't show

**Expected behavior**
I can see DMusic window

 OS: [Windows 10/11 x64]
 Version [Release 0.2]

**Comment by iroxville** [comment]
confirm

**Comment by levovix0** [comment]
It is strange error.
Seems like simplest way to fix it for now is [build DMusic from source code](https://github.com/levovix0/DMusic/wiki/Building-on-Windows)
