### ISSUE TITLE
Save all tracks

### ISSUE THREAD

**Issue by Mostik** [levovix0/DMusic#6]
**Describe the bug**
The download of the track is interrupted at the very beginning

**To Reproduce**
1. Go to Settings panel
2. Checked the checkbox on "Save all tracks"
3. Listened to the track
4. In folder ".../yandex" are no full tracks files
5. Error in console [Additional context]
6. Try run track with player

**Expected behavior**
Full tracks files.

**Screenshots**

 - OS: [Windows 11 x64]
 - Version [master]

**Additional context**
![image](https://user-images.githubusercontent.com/51542168/134930783-85d5a2be-f83c-47b5-804b-834348932b6e.png)
![image](https://user-images.githubusercontent.com/51542168/134930873-3d983836-ae26-4670-b57d-007345286579.png)
![image](https://user-images.githubusercontent.com/51542168/134930948-5a8cb681-61cf-41f5-93d8-274cd6577b2f.png)

**Comment by levovix0** [comment]
Try to install [K-Lite Codec Pack](https://www.codecguide.com/download_kl.htm), this may be same error as #4

**Comment by Mostik** [comment]
> Try to install [K-Lite Codec Pack](https://www.codecguide.com/download_kl.htm), this may be same error as #4

The problem hasn't gone away.

**Comment by levovix0** [comment]
Is there anyone who get this error today?
