### ISSUE TITLE
Ничего не работает

### ISSUE THREAD

**Issue by fLAki1x** [levovix0/DMusic#7]
Не работает не одна кнопка в программе, в чем может быть проблема? 0 реакции на нажатие прослушать плейлист и другие кнопки.
![image](https://user-images.githubusercontent.com/73881770/137860805-51676329-e7f1-4906-8b07-6e0564942a39.png)
 - OS: Windows 10 Pro, 21H1, 19043.1237
 Установлен Python 3.9

**Comment by levovix0** [comment]
У версии, висящей в релизе, еще не было вкладки настроек, из-за чего для того, чтобы войти надо было прописать в settings.json токен от api яндекс музыки.
